apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Namespace}}-configmap
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  CloudMode: "True"
immutable: true