apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Namespace}}-ingress
  namespace: {{.Release.Namespace}}
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: duplo-cert
    appgw.ingress.kubernetes.io/health-probe-path: /default.html
    appgw.ingress.kubernetes.io/use-private-ip: 'false'
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Namespace}}-svc
                port:
                  name: {{ .Values.service.PTD_WEB_APP.name }}
