apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    my-tag1: tousif
    my-tag2: test
spec:
  storageClassName: {{.Release.Namespace}}-windows
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.storage_request_size}}