apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Namespace }}-secretstore-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Namespace }}-kv-secret
    type: Opaque
    data:
    - objectName: ProfileTailorConnectionString
      key: ProfileTailorConnectionString
    - objectName: duplo
      key: duplo
  parameters:
    keyvaultName: {{ .Values.keyVaultName }}
    objects: |
      array:
        - |
          objectName: ProfileTailorConnectionString
          objectType: secret
        - |
          objectName: duplo
          objectType: secret
    tenantId: {{ .Values.tenantId }}
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: {{ .Values.clientId }}
