apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Namespace}}-svc
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 8 }}
spec:
  ports:
    - name: {{ .Values.service.PTD_WEB_APP.name }}
      port: {{ .Values.service.PTD_WEB_APP.port }}
      targetPort: {{ .Values.service.PTD_WEB_APP.targetPort }}
      protocol: {{ .Values.service.PTD_WEB_APP.protocol }}
    # - name: {{ .Values.service.PTD_WORKER_SERVICE.name }}
    #   port: {{ .Values.service.PTD_WORKER_SERVICE.port }}
    #   targetPort: {{ .Values.service.PTD_WORKER_SERVICE.targetPort }}
    #   protocol: {{ .Values.service.PTD_WORKER_SERVICE.protocol }}
  
  type: {{ .Values.service.type}}
  selector:
    app.kubernetes.io/name: {{.Release.Namespace}}-statefulset

